[build]
  command = "cd ski-resort-frontend && npm install && npm run build"
  publish = "ski-resort-frontend/build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9.18"
  PIP_USE_PEP517 = "true"

[[plugins]]
  package = "@netlify/plugin-python-core"

[functions]
  runtime = "python3.9" 